@startuml

title __GRAPH's Class Diagram__\n

  namespace Graph {
    class Graph.BreadthFirstSearch {
        {static} + breadthFirstSearch()
        + test()
    }
  }
  

  namespace Graph {
    class Graph.DepthFirstSearch {
        - discoverIndex : int
        - discoveryOrder : int[]
        - finishIndex : int
        - finishOrder : int[]
        - parent : int[]
        - visited : boolean[]
        + DepthFirstSearch()
        + DepthFirstSearch()
        + depthFirstSearch()
        + getDiscoverIndex()
        + getDiscoveryOrder()
        + getFinishIndex()
        + getFinishOrder()
        + getGraph()
        + getParent()
        + getVisited()
        + test()
    }
  }
  

  namespace Graph {
    interface Graph.DynamicGraph {
        {abstract} + addEdge()
        {abstract} + addVertex()
        {abstract} + exportMatrix()
        {abstract} + filterVertices()
        {abstract} + newVertex()
        {abstract} + printGraph()
        {abstract} + removeEdge()
        {abstract} + removeVertex()
        {abstract} + removeVertex()
    }
  }
  

  namespace Graph {
    class Graph.Edge {
        {static} - UNWEIGHTED_EDGE : double
        - dest : int
        - source : int
        - weight : double
        + Edge()
        + Edge()
        + equals()
        + getDest()
        + getSource()
        + getWeight()
        + hashCode()
        + toString()
    }
  }
  

  namespace Graph {
    interface Graph.Graph {
        {abstract} + edgeIterator()
        {abstract} + getEdge()
        {abstract} + getNumV()
        {abstract} + insert()
        {abstract} + isDirected()
        {abstract} + isEdge()
    }
  }
  

  namespace Graph {
    class Graph.Vertex {
        {static} - UNWEIGHTED_VERTEX : double
        - id : int
        {static} - instanceCounter : int
        - label : String
        - values : HashMap<String, String>
        - weight : double
        + Vertex()
        + Vertex()
        + getID()
        + getLabel()
        + getValue()
        + getWeight()
        + setID()
        + setLabel()
        + setValue()
        + toString()
    }
  }
  

  Graph.DepthFirstSearch o-- Graph.Graph : graph


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
